# Fonts are implemented via Pack.__css__, so this class doesn't need to do anything.
class Font:
    def __init__(self, *args, **kwargs): ...

    def load_predefined_system_font(self): ...

    def load_user_registered_font(self): ...

    def load_arbitrary_system_font(self): ...
