# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    # Docs are always built on Python 3.13. See also the tox config.
    python: "3.13"
  jobs:
    pre_install:
      - python -m pip install --upgrade pip
      - python -m pip install --group 'tox-uv'
    pre_build:
      - python -m tox -e docs-lint
    build:
      html:
        - python -m tox -e docs-$READTHEDOCS_LANGUAGE -- --output=$READTHEDOCS_OUTPUT/html/
