[global]
flavor = "mkdocs"
include = ["**/*.md"]
exclude = ["CONTRIBUTING.md", "README.md", "changes/template.md", "winforms", "comment.md"]
respect-gitignore = true
force-exclude = true

# Disable rules:
# MD013: Line length - flagging on mkdocstrings content
# MD014: Forces commands in codeblocks to show output
# MD042: Empty link - buggy, still flagging on valid MkDocs formatting
# MD052: Reference link not found - buggy, flagging on valis MkDocs links
disable = ["MD013", "MD014", "MD042", "MD052"]

[per-file-ignores]
"changes/**/*.md" = ["MD041"]

#[MD013]  # Line length
#line_length = 999999  # Force reflow to paragraph content to remove linebreaks
#reflow = true
#reflow_mode = "normalize"

[MD026]  # Remove punctuation at the end of headings
punctuation = ",;:"

[MD033]  # No inline HTML
allowed_elements = ["nospell",]  # pyspelling inline disable tag

[MD046]
style = "fenced"
