from rubicon.java import JavaClass

Bitmap = JavaClass("android/graphics/Bitmap")
BitmapFactory = JavaClass("android/graphics/BitmapFactory")
Color = JavaClass("android/graphics/Color")
DashPathEffect = JavaClass("android/graphics/DashPathEffect")
Drawable = JavaClass("android/graphics/drawable/Drawable")
Matrix = JavaClass("android/graphics/Matrix")
Paint = JavaClass("android/graphics/Paint")
Path = JavaClass("android/graphics/Path")
Path__Direction = JavaClass("android/graphics/Path$Direction")
Paint__Style = JavaClass("android/graphics/Paint$Style")
PorterDuff__Mode = JavaClass("android/graphics/PorterDuff$Mode")
PorterDuffColorFilter = JavaClass("android/graphics/PorterDuffColorFilter")
Rect = JavaClass("android/graphics/Rect")
Typeface = JavaClass("android/graphics/Typeface")
