# flake8: noqa
"""
isort:skip_file
"""
from toga.app import App as App
from toga.app import DocumentApp as DocumentApp
from toga.colors import hsl as hsl
from toga.colors import hsla as hsla
from toga.colors import rgb as rgb
from toga.colors import rgba as rgba
from toga.command import Command as Command
from toga.command import Group as Group
from toga.dialogs import ConfirmDialog as ConfirmDialog
from toga.dialogs import ErrorDialog as ErrorDialog
from toga.dialogs import InfoDialog as InfoDialog
from toga.dialogs import OpenFileDialog as OpenFileDialog
from toga.dialogs import QuestionDialog as QuestionDialog
from toga.dialogs import SaveFileDialog as SaveFileDialog
from toga.dialogs import SelectFolderDialog as SelectFolderDialog
from toga.dialogs import StackTraceDialog as StackTraceDialog
from toga.documents import Document as Document
from toga.documents import DocumentWindow as DocumentWindow
from toga.fonts import Font as Font
from toga.icons import Icon as Icon
from toga.images import Image as Image
from toga.keys import Key as Key
from toga.statusicons import MenuStatusIcon as MenuStatusIcon
from toga.statusicons import SimpleStatusIcon as SimpleStatusIcon
from toga.types import LatLng as LatLng
from toga.types import Position as Position
from toga.types import Size as Size
from toga.widgets.activityindicator import ActivityIndicator as ActivityIndicator
from toga.widgets.base import Widget as Widget
from toga.widgets.box import Box as Box
from toga.widgets.button import Button as Button
from toga.widgets.canvas import Canvas as Canvas
from toga.widgets.box import Column as Column
from toga.widgets.dateinput import DateInput as DateInput
from toga.widgets.detailedlist import DetailedList as DetailedList
from toga.widgets.divider import Divider as Divider
from toga.widgets.imageview import ImageView as ImageView
from toga.widgets.label import Label as Label
from toga.widgets.mapview import MapPin as MapPin
from toga.widgets.mapview import MapView as MapView
from toga.widgets.multilinetextinput import MultilineTextInput as MultilineTextInput
from toga.widgets.numberinput import NumberInput as NumberInput
from toga.widgets.optioncontainer import OptionContainer as OptionContainer
from toga.widgets.optioncontainer import OptionItem as OptionItem
from toga.widgets.passwordinput import PasswordInput as PasswordInput
from toga.widgets.progressbar import ProgressBar as ProgressBar
from toga.widgets.box import Row as Row
from toga.widgets.scrollcontainer import ScrollContainer as ScrollContainer
from toga.widgets.selection import Selection as Selection
from toga.widgets.slider import Slider as Slider
from toga.widgets.splitcontainer import SplitContainer as SplitContainer
from toga.widgets.switch import Switch as Switch
from toga.widgets.table import Table as Table
from toga.widgets.textinput import TextInput as TextInput
from toga.widgets.timeinput import TimeInput as TimeInput
from toga.widgets.tree import Tree as Tree
from toga.widgets.webview import WebView as WebView
from toga.window import MainWindow as MainWindow
from toga.window import Window as Window
