name: Build status
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install pytest-tldr
        python -m pip install -e src/core
        python -m pip install -e src/dummy
    - name: Test
      run: |
        cd src/core
        python setup.py test
