name: PR Checklist

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  check-pr-template:
    name: Check PR template
    uses: ./.github/workflows/pr-checklist.yml
